name: Continuous Integration Workflow

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [push]

env:
  CI: true
  DISPLAY: ':99.0'
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
  COVERALLS_GIT_BRANCH: master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.14.2]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: export display
      run: |
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo ">>> Started xvfb"

    - name: npm install
      run: |
        npm install
        npm run clean
        npm i --workspaces
        npm run compile --workspaces

    - name: npm build
      run: |
        ls -la node_modules/@smelly
        npm run vscode:prepublish --workspace=vscode

    - name: npm test
      if: github.ref != 'refs/heads/main'
      run: |
        npm run test --workspaces

    - name: npm coverage
      if: github.ref == 'refs/heads/main'
      #npm run coveralls --workspace=vscode
      run: |
        npm run test --workspaces

    - name: npm package standalone extension
      if: github.ref == 'refs/heads/main'
      run: |
        npm i -g vsce
        npm run generate:vsix --workspace=vscode

    - name: store artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v2
      with:
        name: smelly-test-vscode-extension
        path: ./vscode/*.vsix
