name: Deploy Extension

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: |
          npm i --workspaces
          npm run compile --workspaces
          npm install -g vsce
          cd vscode && npx vsce publish -p ${{ secrets.VSCE_TOKEN }}