name: Publish to Open VSX Registry

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Environment Variables
      uses: tw3lveparsecs/github-actions-setvars@v0.1
      with:
        envFilePath: ./envvars.for.actions

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Build
      run: |
        npm i
        npm i --workspaces
        npm run compile --workspaces
    
    - name: Publish to Open VSX Registry
      uses: HaaLeo/publish-vscode-extension@v1
      with:
        packagePath: ./vscode
        pat: ${{ secrets.VSX_TOKEN }}