name: Publish Package to npmjs

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set Environment Variables
      uses: tw3lveparsecs/github-actions-setvars@v0.1
      with:
        envFilePath: ./envvars.for.actions

    - name: Publish to npm
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: 'https://registry.npmjs.org'
      run: |
        npm i --workspaces
        npm run compile --workspace=cli
        npm publish --workspace=cli --provenance --access public
