name: Publish to Microsoft Marketplace

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Environment Variables
      uses: tw3lveparsecs/github-actions-setvars@v0.1
      with:
        envFilePath: ./envvars.for.actions

    - name: Use Node.js
      with:
        node-version: ${{ env.NODE_VERSION }}
      run: |
          npm i --workspaces
          npm run compile --workspaces
          npm install -g vsce
          cd vscode && npx vsce publish -p ${{ secrets.VSCE_TOKEN }}