name: Deploy Extension

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./vscode

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: |
          npm install
          npm install -g vsce
          npx vsce publish -p ${{ secrets.VSCE_TOKEN }}