name: Publish to Open VSX Registry

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./vscode

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          packagePath: ./vscode
          pat: ${{ secrets.VSX_TOKEN }}